### ISSUE TITLE
{BUG反馈}API key错误

### ISSUE THREAD

**Issue by 1253298081** [solstice23/gpt-trans-netease#3]
4 Your Eyez Only
Onenul API responded:{'error :{'mesage " incorrect API key provided:sk-Jymqb.********************************************it07.
You can find your API key at https://platform. openai.com/account/api-keys.'", type" :"invalid request_error"', ' paran : null,
"code" :"invalid_api_key }}

**Comment by solstice23** [comment]
检查 Key 是否写错

**Comment by 1253298081** [comment]
> 检查 Key 是否写错

public API endpoint URL:https://chatgpt-api.shn.hk/v1/

**Comment by 1253298081** [comment]
> 检查 Key 是否写错
我必须要自己有GPT账号才能用这个翻译吗

**Comment by solstice23** [comment]
@1253298081 公用API可能因为用的人过多用完了
