### ISSUE TITLE
有错误，使用不了翻译

### ISSUE THREAD

**Issue by wdsdw7586** [solstice23/gpt-trans-netease#4]
![微信截图_20230428121810](https://user-images.githubusercontent.com/129982198/235053101-14c6787e-73c1-48db-9d69-8ac222164b1d.png)
![微信截图_20230428121810](https://user-images.githubusercontent.com/129982198/235053128-78930947-b9d0-4b88-82a9-251f1d9d3daa.png)

**Comment by solstice23** [comment]
需要提供自己的 api key
